import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster"
 
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex max-h-screen flex-col items-center bg-[rgb(2,0,36)] from-transparent justify-center p-4">
        {children}
        </main>
        <Toaster />
        </body>
    </html>
  );
}
